apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: sibendudas/grpcenvoy/orderservice
        ports:
        - name: grpc
          containerPort: 8980
---
kind: Service
apiVersion: v1
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  type: ClusterIP
  selector:
    app: orderservice
  ports:
  - name: grpc
    port: 8980
    targetPort: grpc
    protocol: TCP